version: '2'

services:

  server:
    image: mhart/alpine-node
    volumes:
      - ./src:/src
    ports:
      - 3497:80
    working_dir: /src
    command: "npm run start"
    env_file: ./secrets.env
